### ISSUE TITLE
veolia eau IDF

### ISSUE THREAD

**Issue by teuf93** [tetienne/veolia-custom-component#15]
Bonjour et super projet
Y a t'il une variante pour le VEOLIA Ile de France (www.sedif.fr) ?
merci

**Comment by tetienne** [comment]
N'ayant accès qu'à Veolia méditerranée, je n'ai pas pu faire d'autre intégration. S'agit il de ce site ?

https://www.vedif.eau.veolia.fr

**Comment by tetienne** [comment]
Si oui voir ici: https://github.com/tetienne/python-veolia-api/issues/22

**Comment by teuf93** [comment]
Oui, merci c'est bien cela.
