### ISSUE TITLE
FR: https://www.service.eau.veolia.fr/home.html

### ISSUE THREAD

**Issue by lseufer** [tetienne/veolia-custom-component#16]
Est-il possible d'adapter cette intégration pour le site national de Véolia https://www.service.eau.veolia.fr/home.html

Merci !

**Comment by tetienne** [comment]
N'ayant pas accès à cette version, il me faudra une aide pour savoir comment le site (via quelle requête) récupére les informations. 

Je ne suis pas contre l'idée en tout cas. Cela a du sens.

**Comment by lseufer** [comment]
Pas de souci pour l’aide, mais il faudra me guider un peu.

**Comment by 69homee** [comment]
Je veux bien filer un coup de main pour élargir le champ d'application ;-)

**Comment by tetienne** [comment]
@69homee Cela serait avec plaisir.
@lseufer Sur le site comment se présente la récupération des données? Peut-on télécharger un CSV? Y a t il un tableau sur une page avec l’historique?

**Comment by 69homee** [comment]
@tetienne sur https://www.service.eau.veolia.fr/, login n'est pas un numéro de contrat à 7 chiffres mais une adresse mail.
Personnellement, mes factures ne mentionnent pas un numéro de contrat mais une référence de 16 chiffres.

Ensuite dans l'espace perso, on a bien un graph 
![graph](https://user-images.githubusercontent.com/67924280/108872023-0c166480-75fa-11eb-8f02-80be897ffef7.jpg)

**Comment by 69homee** [comment]
@tetienne et un consommation.xls à télécharger
![conso](https://user-images.githubusercontent.com/67924280/108872531-8c3cca00-75fa-11eb-83f6-b7156edaa91d.jpg)

**Comment by tetienne** [comment]
Parfait. Pourrais-tu en utilisant l'onglet Réseau de ton navigateur (qui apparaît en faisant F12) repérer la requête qui part lorsque tu exportes les données au format xsl? Une fois trouvée, clic droit dessus, copier en tant que commande cURL (n'oublie pas d'enlever les informations personnelles)

**Comment by 69homee** [comment]
Dsl mais je ne vois pas de requête partir. Lorsque la page est chargée, je clique sur le bouton d'export, le xls se télécharge mais cela ne génère pas requête supplémentaire... ???

**Comment by 69homee** [comment]
En tout cas, merci de te pencher sur le sujet et pour ton aide ;)

**Comment by lseufer** [comment]
C'est assez hallucinant, Veolia semble avoir une plateforme par régie toute sur la même base mais bidouillée en fonction de la localité. 
Chez moi il s'agit aussi de mon adresse email et de mon mot de passe pour m'identifier. 

Puis sous l'onglet consommation:  https://www.service.eau.veolia.fr/home/espace-client/votre-consommation.html j'ai accès à un tableau mais aucun export n'est dispo. 

La fonctionnalité est bien présente , si je vais sur https://www.service.eau.veolia.fr/home/espace-client/votre-consommation.exportConsommationData.do?vueConso=historique j'ai bien un xls qui est téléchargé mais il est vide.

 Je ne sais pas comment fonctionne ton intégration, si elle est similaire à celle-ci https://community.jeedom.com/t/plugin-veolia-eau-plugin-veolia-eau-narrive-pas-a-se-connecter/17839/37 alors cela ne fonctionnera pas pour moi.

Dans mon ca sil faudrait parser le site pour récupérer les infos de div name="consoFacture" id="consoFacture" class="onglet". Si c'est possible dis moi de quelles info tu as besoin et je te les fournirai, sinon merci pour ton aide !

**Comment by jejeaure** [comment]
Bonjour, intégration intéressante mais comme d'hab ça bug chez moi, j'ai réussi a tout installé ce qui n'était pas gagné, mais bravo les explications sont simple donc j'ai tout, j'ai pu mettre mon identifiant (7 chiffres) et mdp j'ai deux entités qui s'affiche 
`Indisponible
sensor.veolia_daily_consumption
Veolia

veolia_monthly_consumption
sensor.veolia_monthly_consumption
Veolia`

une qui est indispo et l'autre où il affiche zéro litre, comme j'ai pu voir plus haut cela dépend du site internet car le mien est :
https://www.eau-services.com/mon-espace-perso.aspx
J'aimerai savoir si c'est paramétrable ou pas ?
Merci d'avance et bravo pour le TAF

**Comment by tetienne** [comment]
@jejeaure Merci d'ouvrir un autre ticket afin de ne pas mélanger les sujets.

**Comment by tetienne** [comment]
@lseufer  Je zieute justement comment s'y prennent les autres solutions domotiques. J'aimerai éviter le web scrapping car HA ne l'autorise pas pour ses intégrations. Par contre le lien que tu donnes est pour Veolia IDF. Il s'agit de ce site? https://espace-client.vedif.eau.veolia.fr

**Comment by lseufer** [comment]
Mince je pense que c'est mort alors :-/ parce qu'au vu du foutoir qu'est leur gestion informatique nous ne sommes pas près d'avoir une API... 
Un mauvais copier-coller pour le lien vers le forum de Jeedom, je faisais référence au plugin en lui même qui utilise https://www.service.eau.veolia.fr/ et pas au (vilain) parisien qui demande à ce que le plugin soit adapté à la plateforme spécifique à l'ile de France.

**Comment by McRMX** [comment]
Bonjour,

la commande cURL vous intéresse-t-elle toujours ?

J'ai trouvé comment la faire, je ne sais pas quoi enlever exactement au niveau des info perso!!

J'ai vu adresse / adresse mail / N° de compteur / pas vu de mot de passe


Voulez-vous que je vous le partage sur discord pour que vous puissiez m'aiguiller en même temps ?

**Comment by ghost** [comment]
Bonjour,

Je me permets de relancer le sujet étant moi même intéressé pour https://www.service.eau.veolia.fr/.

Je suis intégralement disponible pour toutes aides sur le sujet...

Merci d'avance
