### ISSUE TITLE
Intégration eau du grand lyon

### ISSUE THREAD

**Issue by Fx-18** [tetienne/veolia-custom-component#24]
Bonjour,

Est-il possible de modifier (ou de faire évoluer) le plug-in pour le brancher sur Eau-du-grand Lyon (https://agence.eaudugrandlyon.com) ?
La lecture des différents fichiers ne m'a pas laissé de pistes sérieuse.
Ancien utilisateur de domoticz, j'avais réussi à modifier le code pour l'adapter au service.
A savoir que Eau du Grand Lyon utilise aussi un identifiant sur 7 chiffres (et comme les autres régies, leur site ressemble fortement à celui de Veolia)

A disposition si je peux aider à tester, merci d'avance si ce sujet vous intéresse!

**Comment by tetienne** [comment]
Je viens de regarder un peu ce qui ce se fait ailleurs, et pour Eau du grand Lyon, il semblerait que juste changer l’url suffirait. Je le vois par exemple ici: https://github.com/NextDom/plugin-veolia_eau/blob/7e4ce4b61ed3eaa6088655615398ba19dc514c3f/core/class/veolia_eau_process.class.php#L337

Je vais essayer de me trouver du temps dans la semaine pour implémenter ça.

**Comment by Fx-18** [comment]
OK, merci beaucoup pour la réactivité!

**Comment by mathep34** [comment]
Bonjour
je pense que j'ai le meme probleme de FX-18 sur Lyon, moi c'est dans le sud avec cette adresse : https://www.eau-services.com.
Merci a vous

**Comment by tetienne** [comment]
@Fx-18 Désolé pour l’énorme retard sur ta requête. Je ne me suis donné le temps pour. mais c’est bien bientôt chose faite. Si tu as des connaissances en Python, te serait-il possible de tester cette brancher de mon API: https://github.com/tetienne/python-veolia-api/pull/115 ?
Si non, te serait-il possible de me contacter sur le [discord de HA](https://discord.com/invite/home-assistant) pour donner les accès à ton compte (en ayant par exemple changer temporairement le mot de passe).

**Comment by Fx-18** [comment]
Bonjour @tetienne , à mon tour d'être désolé du retard :)
J'avais abandonné mon projet de migration sous HA, mais j'y reviens. J'ai vu que le plugin (et HA aussi) avait bien évolué.
Possible d'étudier l'implémentation du site https://agence.eaudugrandlyon.com/ qui semble être très proche du site fonctionnel : https://www.eau-services.com/

Merci d'avance
