### ISSUE TITLE
Plusieurs Veolia(s)?

### ISSUE THREAD

**Issue by r-jean-pierre** [tetienne/veolia-custom-component#30]
Bonjour,

Pour ma commune, je dois me connecter sur https://www.service.eau.veolia.fr
C'est presque pareil que ce qu'on trouve dans la documentation du composant (https://www.eau-services.com ), mais pas exactement
D'ailleurs on a pas de numéro client (cherché comme un fou sur toutes mes factures), on entre son mail et pas un nombre à 7 chiffres

Comment peut-on faire? c'est réellement 2 sites (comme si on avait 2 fournisseurs différents) ou y'a une bete astuce et je m'excuse si je suis passé à coté...

PS une fois loggué on a bien sa consommation journalière sur "le" site véolia

**Comment by r-jean-pierre** [comment]
Si ça peut aider, j'suis allé faire un tour sur mon compte et je vois que, une fois connecté, ceci:

https://www.service.eau.veolia.fr/home/espace-client/votre-consommation.exportConsommationData.do?vueConso=historique

donne directement les 3 derniers mois de conso jour par jour dans un CSV en bonne et due forme 

Et ce lien
https://www.service.eau.veolia.fr/home/espace-client/votre-consommation.html?vueConso=historique

Un html ou les données sont dans une table html bien régulière, à base de TR TD, sans offuscation que de soit

Si qqc est prévu, je me porte volontaire pour tester, à défaut de pas savoir programmer assez bien

**Comment by lhanneus** [comment]
Je plussoie la demande. D'autres personnes n'ont accès qu'à https://www.service.eau.veolia.fr/

**Comment by m4h3** [comment]
Pour l'autre portail, il faut utiliser https://github.com/kugan49/veolia-custom-component-HACS

**Comment by lhanneus** [comment]
> Pour l'autre portail, il faut utiliser https://github.com/kugan49/veolia-custom-component-HACS

Un énorme merci @m4h3 , ça fonctionne pour moi !
