### ISSUE TITLE
Possible d'avoir l'intégration pour Veolia IDF?

### ISSUE THREAD

**Issue by jax93300** [tetienne/veolia-custom-component#31]
Bonjour,

Merci pour le travail, est-il possible de faire fonctionner l'intégration pour le site IDF :  

https://espace-client.vedif.eau.veolia.fr/

Merci

**Comment by tetienne** [comment]
Malheureusement, cela s’avère assez compliqué: https://github.com/tetienne/python-veolia-api/issues/22

**Comment by bilbon0bud** [comment]
Bonjour

Est ce que ce plugin jeedom pourrait aider a ajouter cette intégration dan Home Assistant
https://github.com/Aegis940/plugin-teleo/blob/beta/resources/get_veolia_idf_consommation.py

**Comment by tetienne** [comment]
@bilbon0bud hello, malheureusement, ce plugin fait ce qui est interdit par HA, du web scrapping: https://github.com/Aegis940/plugin-teleo/blob/beta/resources/get_veolia_idf_consommation.py#L133
C’est à dire ouvrir un navigateur est simulé un utilisateur.

**Comment by bilbon0bud** [comment]
Ok merci pour le retour. j en avais pas fais attention a ce detail.
