### ISSUE TITLE
Integration with So'Bass

### ISSUE THREAD

**Issue by BrainPonders** [tetienne/veolia-custom-component#32]
Hi is there any connection with Si'Bass https://www.service.eau.veolia.fr and can I make this integration work with that?

I tried to create an account on https://www.eau-services.com but the contract No and Facture reference doesn't seem to match.

**Comment by tetienne** [comment]
Est-ce que So’Bass est un service de Veolia? Si non, cela ne rentre pas dans le cadre de cette intégration.

**Comment by BrainPonders** [comment]
Je ne connais pas la construction exacte. Mais ma page de connexion fait partie du domaine Veolia et leur logo est bien visible.

J'espérais que vous compreniez mieux.

**Comment by tetienne** [comment]
C’est une filiale de Veolia apparrement. Sur ce site, peut-on récupérer la consommation en téléchargeant un fichier csv ou autre ?

**Comment by BrainPonders** [comment]
Oui, je peux télécharger un fichier csv

![image](https://user-images.githubusercontent.com/5793189/139528261-497fa9e7-8e70-4cee-acdc-c5d5eef67044.png)

Et le contenu ressemble à ceci :

Date de   relev�;Index relev� (litres);Consommation du jour (litres);Index   Mesur�/Estim�
--01/08/2021;1132136;458;M
02/08/2021;1132303;167;M
03/08/2021;1133560;1257;M
04/08/2021;1133568;8;M
05/08/2021;1134138;570;M

**Comment by BrainPonders** [comment]
Pensez-vous que votre composant peut fonctionner avec le portail So'Bass ?

**Comment by tetienne** [comment]
Te serait-il possible de me rejoindre sur le Discord de [Home Assistant](https://discord.com/invite/home-assistant) et me partager tes identifiants (en ayant changer le mot de passe temporairement par exemple) ? Cela me permettrait de comprendre rapidement comment récupérer les informations.

**Comment by simongautier57** [comment]
Bonjour Tetienne, 
merci  pour vos contributions. 
Je crois que j'ai la même question que eRJe79, meme portail  https://www.service.eau.veolia.fr . 
Après vos tests, avez vous trouvé que cela peut marcher? 
SI nécessaire, je peux mettre mes identifiants à dispo temporairement. 
Merci d'avance pour votre réponse. 
Simon

**Comment by BrainPonders** [comment]
> Te serait-il possible de me rejoindre sur le Discord de [Home Assistant](https://discord.com/invite/home-assistant) et me partager tes identifiants (en ayant changer le mot de passe temporairement par exemple) ? Cela me permettrait de comprendre rapidement comment récupérer les informations.

Oui, je peux, faites-moi juste savoir quand et je vous rejoindrai là-bas.

**Comment by mrwiwi** [comment]
Hey, je venais également demander :) Je peux aussi vous joindre ! ^^

**Comment by mrwiwi** [comment]
@tetienne est ce que tu continues le projet ? Dis nous sinon sur quels fichiers on doit cibler les modifications nécessaires s'il te plaît, ça serait cool ! :)

**Comment by tetienne** [comment]
@mrwiwi Je ne suis pas en effet très actif, voir pas du tout, sur ce composant. Ma vie perso, et mon travail m’occupe pas mal en ce moment, j’ai moins de temps de libre.
De plus, je suis plus occupé par ce composant que je maintiens également:https://github.com/iMicknl/ha-tahoma/
Mais vous pouvez me contacter sur le Discord de HA afin de me partager vos login/password afin que je puisse voir comment récupérer les info.
