### ISSUE TITLE
Erreur après migration a HA 2022.11.1

### ISSUE THREAD

**Issue by hugoKs3** [tetienne/veolia-custom-component#34]
Bonjour, 

Suite à la dernière mise à jour de Home Assistant, l'intégration Veolia ne fonctionne plus avec le code d'erreur suivant:

Setup failed for custom integration veolia: Requirements for veolia not found: ['pyolia==0.2.1'].

**Comment by mathep34** [comment]
Bonjour,
même problème même message d'erreur. J'ai déactivé l'integration.

**Comment by hugoKs3** [comment]
J'ai réussi a le faire marcher en utilisant la modification de @ghost58400 dans son fork:

https://github.com/ghost58400/veolia-custom-component

**Comment by tetienne** [comment]
Hello à tous 👋

Vraiment désolé pour mon silence. Il m'est difficile d'attribuer du temps sur cette integration. Je maintiens principalement Overkiz (Somfy, Cozytouch, etc) et Toshiba AC quand j'ai un moment de libre.

@ghost58400 je viens de merger ta PR sur eau du grand Lyon.
Je ferai une release lundi.

N'hésite pas à backporter tes modifications ici.

Sinon, je regarderai pour vite corriger ce problème dans la semaine.

**Comment by mathep34** [comment]
Bonjour "tetienne"
peux-tu nous dire si tu vas pouvoir corriger ce problème, ou si tu nous conseilles de trouver une autre solution pour avoir des data Veolia dans Home Assistant ?
Merci a toi 
Pierre

**Comment by tetienne** [comment]
@mathep34 Je tente de regarder ça la semaine prochaine 🙏

**Comment by mathep34** [comment]
@tetienne , 
coucou as-tu un peu de temps pour trouver une solution, ou donne nous un conseil/avis si on doit abandonner ta solution ?
Merci encore pour ton travail.

**Comment by tetienne** [comment]
Oui j'ai pris un peu de temps pour mettre à jour la librairie utiliser par le composant. Malheureusement, toujours le même soucis alors que les autres composants que je maintiens n'ont pas le problème. Je cherche encore.

**Comment by tetienne** [comment]
J’ai pu finalement corriger le soucis. Vous pouvez installer la dernière version. Encore désolé pour ce très long délai.

**Comment by mathep34** [comment]
merci a toi
j'applique ce soir

**Comment by mathep34** [comment]
tout re-fonctionne parfaitement.
merci
