### ISSUE TITLE
Do not work in the Energy dashboard

### ISSUE THREAD

**Issue by MassimoL06** [tetienne/veolia-custom-component#35]
Hello
thanks for this cool integration !
The Energy dashboard inlcudes also water consomption.
But I am not able to integrate the values from Veolia in the dashboard.
Please help.

**Comment by tetienne** [comment]
Hi, 

Indeed, water consumption has been added recently. But I’m worry about the fact the data Veolia returns us are 3 days old. So the data displayed in the Dashboard will be "wrong". There is no way to change this behavior sadly.
