### ISSUE TITLE
Hourly values report incoherent values

### ISSUE THREAD

**Issue by Jezza34000** [tetienne/veolia-custom-component#42]
Hello,
Castelnau-le-lez does not have hourly consumption report, but HA component give values ? : 

![Screenshot from 2023-10-19 11-26-42](https://github.com/tetienne/veolia-custom-component/assets/57314417/5a12ffcc-c392-48a2-bb18-3af7fd968ba1)

![Screenshot from 2023-10-19 11-21-22](https://github.com/tetienne/veolia-custom-component/assets/57314417/0ca34147-96aa-40c6-b446-496302c56c4d)

**Comment by Jezza34000** [comment]
Fixed with my PR : https://github.com/tetienne/python-veolia-api/pull/247

**Comment by Jezza34000** [comment]
Could you merge it ? @tetienne 
Thank you

**Comment by tetienne** [comment]
Thx, that’s weird because I tested it with my own account disabling hourly. I will release a new version soon.

**Comment by tetienne** [comment]
Fix was release.
